name: k8s app

on:
  workflow_dispatch: ~
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  terraform_fmt:
    runs-on: ubuntu-20.04
    name: "Check terraform language style conventions"
    steps:
      - uses: actions/checkout@v3
      - run: |
          terraform fmt -check

  terraform_validation:
    runs-on: ubuntu-20.04
    name: "Validate terraform configuration"
    steps:
      - uses: actions/checkout@v3
      - run: |
          terraform validate

  test:
    runs-on: ubuntu-20.04
    name: "Tests terraform"
    steps:
      - uses: actions/checkout@v3
      - run: |
          terraform test
